---
- name: Install yum utils
  yum:
    name: yum-utils
    state: present

- name: Install epel-release
  yum:
    name: epel-release
    state: present


- name: Instal nfs-utils
  yum:
    name: nfs-utils
    state: latest  

- name: Install python3-pip
  yum: 
    name: python3-pip
    state: present

- name: Install python3-pip
  yum: 
    name: python-setuptools
    state: present
  
- name: Install git
  yum:
    name: git 
    state: present

- name: Ensure user jnvilo exists
  user:
    name: jnvilo
    shell: /bin/bash
    groups: wheel
    uid: 1773

- name: Ensure user calibre exists
  user:
    name: calibre
    groups: jnvilo
    comment: Calibre user


    
- name: checkout calibre-web from git repo
  git:
    repo: https://github.com/janeczku/calibre-web.git
    dest: /home/calibre/calibre-web
    version: master
    update: no
  become: yes
  become_user: calibre
  
- name: Install requirements.txt
  pip:
    executable: pip3
    name: setuptools


- name: Install requirements.txt
  pip:
    requirements: /home/calibre/calibre-web/requirements.txt
    executable: pip3

- name: Ensure /home/calibre/Books exists
  file:
    path: /home/calibre/Books
    state: directory
    owner: calibre
    group: calibre
    mode: 0775
    


- name: Add Books NFS mountpoint 
  lineinfile:
    path: /etc/fstab
    regexp: '^192.168.2.251/Books'
    line: 192.168.2.251:/Books /home/calibre/Books  nfs soft,timeo=30 0 0 

- name: Mount the books on the QNAP [192.168.2.251:/Books /home/calibre/Books  nfs soft,timeo=30 0 0]
  mount:
    path: /home/calibre/Books
    src: 192.168.2.251:/Books
    fstype: nfs
    opts: soft,timeo=30
    state: mounted

- name: Calibre-Web | Create Unit file
  template: src=calibre-web.service.j2 dest=/lib/systemd/system/calibre-web.service mode=644
  notify:
    - reload systemctl

- name: Calibre-web | Start 
  service: name=calibre-web.service state=started enabled=yes

- name: Open Firewall port 8083
  firewalld:
    port: 8083/tcp
    permanent: yes
    state: enabled
  notify:
    - reload firewalld
